# Generated by Django 3.2 on 2022-09-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicroomchatmessage',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
