NO_NEW_GENERAL_NOTIFICAIONS_FOR_THE_USER = -2   
NO_NOTIFICATION_IN_THE_DATABASE = -1
GENERAL_MSG_TYPE_NOTIFICATIONS_PAYLOAD = 0 # new message for notification is incoming 
GENERAL_MSG_TYPE_PAGINATION_EXHAUSTED = 1
GENERAL_MSG_TYPE_NOTIFICATIONS_REFRESH_PAYLOAD = 2
GENERAL_MSG_TYPE_UPDATED_NOTIFCATION = 5 # update a notification that has been altered (Accepted and declined )
DEFAULT_NOTIFICATION_PAGE_SIZE = 5
GENERAL_MSG_TYPE_GET_NEW_NOTIFICATIONS = 3
GENERAL_MSG_TYPE_GET_UNREAD_NOTIFICATIONS_COUNT = 4 

CHAT_MSG_TYPE_NOTIFICATIONS_PAYLOAD = 10